In [ ]:
#@title Configurações

import torch

if torch.cuda.is_available():
    print("CUDA disponível.")
    device = torch.device("cuda")
    torch.set_default_device('cuda')
    print("Usando GPU: ", torch.cuda.get_device_name(0))
else:
    print("CUDA não disponível. Usando CPU...")
    device = torch.device("cpu")

print(f'Semente aleatória inicial: {torch.initial_seed()}')


CUDA disponível.
Usando GPU:  Tesla T4
Semente aleatória inicial: 10076502804165312092


### Questão 1

Crie um tensor random com shape (7,7).

In [ ]:
#@title Resposta 001

tensor_7x7 = torch.rand(7, 7)
print("Tensor 7x7:\n", tensor_7x7)


Tensor 7x7:
 tensor([[0.8890, 0.8258, 0.2533, 0.5004, 0.3152, 0.2725, 0.3277],
        [0.6911, 0.8760, 0.4179, 0.4243, 0.0140, 0.2096, 0.8989],
        [0.1510, 0.1646, 0.1682, 0.7537, 0.9566, 0.2699, 0.7147],
        [0.6261, 0.6405, 0.8040, 0.9150, 0.7678, 0.2787, 0.4768],
        [0.9681, 0.0769, 0.4323, 0.9721, 0.1298, 0.9750, 0.3890],
        [0.7954, 0.6419, 0.2802, 0.8433, 0.1195, 0.8028, 0.9738],
        [0.9245, 0.1780, 0.1571, 0.2323, 0.0538, 0.8058, 0.1745]],
       device='cuda:0')


### Questão 2

Execute uma multiplicação de matrizes no tensor da Questão 1 com outro tensor aleatório com forma (1, 7) (dica: pode ser necessário transpor o segundo tensor).

In [ ]:
#@title Resposta 002

tensor_1x7 = torch.rand(1, 7)
resultado_mul = torch.mul(tensor_7x7, tensor_1x7.t())
print("\nResultado da multiplicação:\n", resultado_mul)



Resultado da multiplicação:
 tensor([[0.8418, 0.7820, 0.2399, 0.4739, 0.2985, 0.2580, 0.3103],
        [0.1158, 0.1468, 0.0700, 0.0711, 0.0023, 0.0351, 0.1507],
        [0.0362, 0.0395, 0.0403, 0.1807, 0.2293, 0.0647, 0.1713],
        [0.1998, 0.2045, 0.2567, 0.2921, 0.2451, 0.0890, 0.1522],
        [0.8141, 0.0647, 0.3635, 0.8174, 0.1091, 0.8199, 0.3271],
        [0.4372, 0.3528, 0.1540, 0.4635, 0.0657, 0.4413, 0.5352],
        [0.8541, 0.1645, 0.1451, 0.2145, 0.0497, 0.7444, 0.1612]],
       device='cuda:0')


### Questão 3

Defina uma semente aleatória como 0 e faça a Questão 1 e Questão 2 novamente.

In [ ]:
#@title Resposta 003

torch.manual_seed(0)
tensor_7x7_seed = torch.rand(7, 7)
tensor_1x7_seed = torch.rand(1, 7)
resultado_mult_seed = torch.mul(tensor_7x7_seed, tensor_1x7_seed.t())
print("\nResultado com seed=0:\n", resultado_mult_seed)



Resultado com seed=0:
 tensor([[0.3880, 0.5023, 0.0242, 0.9140, 0.9196, 0.7746, 0.4035],
        [0.6488, 0.1812, 0.7195, 0.0936, 0.0595, 0.3237, 0.7594],
        [0.0982, 0.0910, 0.4179, 0.2058, 0.1674, 0.2558, 0.3893],
        [0.0693, 0.2536, 0.1416, 0.0699, 0.2180, 0.0546, 0.1402],
        [0.3320, 0.2329, 0.0827, 0.2351, 0.2507, 0.3112, 0.0165],
        [0.0284, 0.2732, 0.3585, 0.1379, 0.0838, 0.2944, 0.2417],
        [0.1587, 0.5382, 0.7341, 0.0454, 0.2565, 0.0471, 0.5371]],
       device='cuda:0')


### Questão 4

Crie dois tensores aleatórios de shape (2,3), carregue-os para GPU e execute a multiplicação de matrizes sobre eles na GPU. Lembre que você precisa habilitar o suporte da GPU no Colab. Defina uma semente aleatória como 1234 na GPU.

In [ ]:
#@title Resposta 004

torch.manual_seed(1234)
if torch.cuda.is_available():
  tensor1_gpu = torch.rand(2, 3)
  tensor2_gpu = torch.rand(2, 3).t()
  resultado_gpu = torch.matmul(tensor1_gpu, tensor2_gpu)
  print("\nResultado na GPU:\n", resultado_gpu)
else:
  print("GPU não disponível.")



Resultado na GPU:
 tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')


### Questão 5

Encontre os valores máximo e mínimo da saída da questão 4.

In [ ]:
#@title Resposta 005

maximo = torch.max(resultado_gpu)
minimo = torch.min(resultado_gpu)
print("Máximo:", maximo.item())
print("Mínimo:", minimo.item())


Máximo: 0.7667766809463501
Mínimo: 0.27863210439682007


### Questão 6
 Encontre os valores dos índices do máximo e mínimo da questão 4.

In [ ]:
#@title Resposta 006

indices_max = torch.argmax(resultado_gpu)
indices_min = torch.argmin(resultado_gpu)
print("Índice do máximo:", indices_max.item())
print("Índice do mínimo:", indices_min.item())


Índice do máximo: 1
Índice do mínimo: 0


### Questão 7

Faça um tensor aleatório com shape (1, 1, 1, 10) e então crie um segundo tensor com todas as dimensões 1 do tensor aleatório removidas para ficar com um tensor da forma (10). Defina a semente como 7 ao criá-lo e imprima o primeiro tensor e sua forma, bem como o segundo tensor e sua forma.

In [ ]:
#@title Resposta 007

torch.manual_seed(7)
tensor_1110 = torch.rand(1, 1, 1, 10)
tensor_10 = tensor_1110.squeeze()
print("\nTensor original:", tensor_1110)
print("Shape original:", tensor_1110.shape)
print("Tensor após squeeze:", tensor_10)
print("Shape após squeeze:", tensor_10.shape)



Tensor original: tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
           0.6333, 0.5733]]]], device='cuda:0')
Shape original: torch.Size([1, 1, 1, 10])
Tensor após squeeze: tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
        0.5733], device='cuda:0')
Shape após squeeze: torch.Size([10])


### Questão 8

* Crie três imagens sintéticas contendo 7 pixels de altura e 7 pixels de largura usando tensores aleatórios. Assuma que os valores de pixels aleatórios são inteiros e variam entre 0 a 255.
* Combine esses três tensores (imagens) em um único tensor maior de rank-3
* Reestruture este tensor de rank-3 de modo que seja adicionada mais uma dimensão de comprimento 1. Esta dimensão deve representar o canal de cor na escala de cinza. Espera-se que este tensor no final tenha o seguinte shape (#N_IMG, #CANAL, #ALTURA, #LARGURA)
* imprima os pixels da primeira imagem
* imprima os pixels da terceira imagem
* imprima os pixels no canal de cor da primeira imagem
* imprima os pixels no canal de cor da terceira imagem
* imprima os pixels das linhas ímpares no canal de cor da primeira imagem
* imprima os pixels das linhas ímpares no canal de cor da terceira imagem
* imprima os pixels das linhas pares no canal de cor da primeira imagem
* imprima os pixels das linhas ímpares no canal de cor da terceira imagem
* imprima os pixels das colunas ímpares no canal de cor da primeira imagem
* imprima os pixels das colunas pares no canal de cor da terceira imagem

In [ ]:
#@title Resposta 008

torch.manual_seed(42)
img1 = torch.randint(0, 256, (7, 7))
img2 = torch.randint(0, 256, (7, 7))
img3 = torch.randint(0, 256, (7, 7))

imagens = torch.stack([img1, img2, img3])
imagens = imagens.unsqueeze(1)

print("\nPrimeira imagem:\n", imagens[0, 0])
print("Terceira imagem:\n", imagens[2, 0])
print("Canal de cor primeira imagem:\n", imagens[0])
print("Canal de cor terceira imagem:\n", imagens[2])
print("Linhas ímpares primeira imagem:\n", imagens[0, 0, ::2])
print("Linhas ímpares terceira imagem:\n", imagens[2, 0, ::2])
print("Linhas pares primeira imagem:\n", imagens[0, 0, 1::2])
print("Linhas ímpares terceira imagem:\n", imagens[2, 0, ::2])
print("Colunas ímpares primeira imagem:\n", imagens[0, 0, :, ::2])
print("Colunas pares terceira imagem:\n", imagens[2, 0, :, 1::2])



Primeira imagem:
 tensor([[ 83, 105, 166, 178,  17, 223,  62],
        [ 44,  12, 193,  25, 225, 253, 242],
        [ 11,  28,  70,  27, 244,  67, 241],
        [128, 137, 111,  53, 203, 156, 140],
        [187, 198, 237, 109, 150,  16,  37],
        [148, 110,  59,  27, 208,  69, 140],
        [105, 153, 156,  23, 251, 138,  20]], device='cuda:0')
Terceira imagem:
 tensor([[ 37, 121,  46, 147, 116, 146, 248],
        [110,  73,  11, 205, 210,  66,  68],
        [253, 232, 218, 136,  64, 164, 203],
        [115,  22, 252, 172,  22,  23, 213],
        [ 71,  41,  99,   3,  96,  26, 179],
        [ 19, 105, 134, 170,  47,  97, 128],
        [ 42, 202, 204,  17, 229,  96,  41]], device='cuda:0')
Canal de cor primeira imagem:
 tensor([[[ 83, 105, 166, 178,  17, 223,  62],
         [ 44,  12, 193,  25, 225, 253, 242],
         [ 11,  28,  70,  27, 244,  67, 241],
         [128, 137, 111,  53, 203, 156, 140],
         [187, 198, 237, 109, 150,  16,  37],
         [148, 110,  59,  27, 208,  

### Questão 9

Crie um tensor que armazene as seguintes estatísticas dos pixels de cada imagem:
* soma das linhas
* soma das colunas
* moda
* média de todos
* desvio padrão

In [ ]:
#@title Resposta 009

estatisticas = {
    'soma_linhas': torch.sum(imagens, dim=3),
    'soma_colunas': torch.sum(imagens, dim=2),
    'moda': torch.mode(imagens.reshape(-1))[0],
    'media': torch.mean(imagens.double()),
    'desvio_padrao': torch.std(imagens.double())
}

print("Estatísticas:")
for k, v in estatisticas.items():
    print(f"{k}:\n{v}")

Estatísticas:
soma_linhas:
tensor([[[ 834,  994,  688,  928,  934,  761,  846]],

        [[ 773,  695, 1018,  799,  674, 1126,  941]],

        [[ 861,  743, 1270,  819,  515,  700,  831]]], device='cuda:0')
soma_colunas:
tensor([[[ 706,  743,  992,  442, 1298,  922,  882]],

        [[1064,  742,  987,  739, 1012,  686,  796]],

        [[ 647,  796,  964,  850,  784,  618, 1080]]], device='cuda:0')
moda:
96
media:
120.74829931972789
desvio_padrao:
74.62911433208882


### Questão 10

Considere o tensor de imagens de rank-4 resultante da questão 8.
Realize a operação de `flatten` somente sobre as matrizes de pixels deste tensor e imprima o tensor resultante. Lembrando que flatten é uma operação sobre tensores que faz com que o shape de um tensor seja igual ao número de elementos contidos nele, ou seja, que transforme as imagens em um tensor de rank-1 (array 1-d).

In [ ]:
#@title Resposta 010

imagens_flat = imagens.reshape(imagens.shape[0], imagens.shape[1], -1)
print("\nTensor após flatten das matrizes de pixels:\n", imagens_flat)
print("\nShape após flatten:", imagens_flat.shape)



Tensor após flatten das matrizes de pixels:
 tensor([[[ 83, 105, 166, 178,  17, 223,  62,  44,  12, 193,  25, 225, 253, 242,
           11,  28,  70,  27, 244,  67, 241, 128, 137, 111,  53, 203, 156, 140,
          187, 198, 237, 109, 150,  16,  37, 148, 110,  59,  27, 208,  69, 140,
          105, 153, 156,  23, 251, 138,  20]],

        [[ 39,  57,  92,  60, 146, 185, 194,  64, 137, 100, 155, 164,   5,  70,
          231, 220, 194, 143,  53,   5, 172,  96,   7, 194, 126, 161, 214,   1,
          191, 160,  29,  54, 129,  48,  63, 191, 158, 149, 172, 207, 137, 112,
          252,   3, 229,  29, 152,  92, 184]],

        [[ 37, 121,  46, 147, 116, 146, 248, 110,  73,  11, 205, 210,  66,  68,
          253, 232, 218, 136,  64, 164, 203, 115,  22, 252, 172,  22,  23, 213,
           71,  41,  99,   3,  96,  26, 179,  19, 105, 134, 170,  47,  97, 128,
           42, 202, 204,  17, 229,  96,  41]]], device='cuda:0')

Shape após flatten: torch.Size([3, 1, 49])
